### ISSUE TITLE
Platform Name

### ISSUE THREAD

**Issue by yangjiel** [paolotremadio/homebridge-automation-presence#5]
Hi there, I'm interested in this homebridge plugin. 
However, there is not enough information to configurate this plugin. 

The issue is:
I tried "platform": "AutomationPresence" but got "No plugin was found for the platform "AutomationPresence" in your config.json. Please make sure the corresponding plugin is installed correctly."

Could you provide the correct platform name for this plugin configuration? Thanks.

**Comment by paolotremadio** [comment]
How have you installed the plugin?

**Comment by yangjiel** [comment]
I installed it from the Homebridge Plugins page.
